Repository seqeralabs/docs, pull requests merged in 2024-08, with the labels that each got.

#150 Updated README with correct publishing info
  README.md
Labels: 1. Editor review

#158 Update: 23.4.x release notes
  platform_versioned_docs/version-23.4.0/enterprise/release_notes/changelog.mdx
  platform_versioned_docs/version-23.4.0/enterprise/release_notes/enterprise_latest.mdx
Labels: 4. Reviews complete

#133 Add metadata.namespace to K8s YAML files
  platform_versioned_docs/version-24.1/enterprise/kubernetes.mdx
Labels: 4. Reviews complete

#163 Add Data Explorer max number of items listed
  platform_versioned_docs/version-24.1/enterprise/configuration/configtables/data_features_yml.yml
  platform_versioned_docs/version-24.1/enterprise/configuration/overview.mdx
Labels: 4. Reviews complete

#165 Changelog - 14 August 2024
  platform_versioned_docs/version-24.1/cloud/changelog.mdx
Labels: 2. Dev/PM review

#168 Add external links to ignore list
  .github/workflows/links.yml
  lychee.toml
Labels: 4. Reviews complete

#174 update connect images used for enterprise
  platform_versioned_docs/version-24.1/enterprise/_templates/docker/docker-compose.yml
  platform_versioned_docs/version-24.1/enterprise/_templates/k8s/data_studios/proxy.yml
  platform_versioned_docs/version-24.1/enterprise/_templates/k8s/data_studios/server.yml
Labels: 1. Editor review

#175 Updated tower_db_url example
  platform_versioned_docs/version-24.1/enterprise/configuration/configtables/req_env_vars.yml
Labels: 4. Reviews complete

#184 Fix CORS JSON for AWS
  platform_versioned_docs/version-23.3/data/data-explorer.mdx
  platform_versioned_docs/version-23.4/data/data-explorer.mdx
  platform_versioned_docs/version-24.1/data/data-explorer.mdx
Labels: 4. Reviews complete

#182 24.1.3 Enterprise patch release guidance and changelog
  platform_versioned_docs/version-24.1/cloud/changelog.mdx
  platform_versioned_docs/version-24.1/enterprise/_templates/docker/docker-compose.yml
  platform_versioned_docs/version-24.1/enterprise/_templates/docker/tower.yml
  platform_versioned_docs/version-24.1/enterprise/_templates/k8s/tower-cron.yml
  platform_versioned_docs/version-24.1/enterprise/_templates/k8s/tower-svc.yml
  platform_versioned_docs/version-24.1/enterprise/index.mdx
  platform_versioned_docs/version-24.1/enterprise/release_notes/enterprise_changelog.mdx
  platform_versioned_docs/version-24.1/enterprise/release_notes/enterprise_latest.mdx
  platform_versioned_docs/version-24.1/enterprise/testing.mdx
  platform_versioned_docs/version-24.1/enterprise/upgrade.mdx
  platform_versioned_sidebars/version-24.1-sidebars.json
Labels: 2. Dev/PM review

#181 Update DRAGEN content and screenshot
  platform_versioned_docs/version-23.3/supported_software/dragen/_images/dragen_ce_ami.png
  platform_versioned_docs/version-23.3/supported_software/dragen/overview.mdx
  platform_versioned_docs/version-23.4/supported_software/dragen/overview.mdx
  platform_versioned_docs/version-24.1/supported_software/dragen/overview.mdx
Labels: 4. Reviews complete

#180 Include behavior when user account is deleted
  platform_versioned_docs/version-24.1/data-privacy/overview.mdx
  platform_versioned_docs/version-24.1/monitoring/audit-logs.mdx
  platform_versioned_docs/version-24.1/monitoring/configtables/log_events.yml
  platform_versioned_docs/version-24.1/orgs-and-teams/organizations.mdx
Labels: 2. Dev/PM review

#177 Fixed outdated URLs
  platform_versioned_docs/version-24.1/enterprise/configuration/configtables/data_features_env.yml
  platform_versioned_docs/version-24.1/enterprise/configuration/configtables/features_env.yml
Labels: 4. Reviews complete

#176 Adjusted incorrect URL
  platform_versioned_docs/version-24.1/enterprise/configuration/configtables/features_env.yml
Labels: 1. Editor review

#189 fix: reference to S3-hosted data in GCP CE docs
  platform_versioned_docs/version-23.1/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-23.2/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-23.3/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-23.4/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-24.1/compute-envs/google-cloud-batch.mdx
Labels: 4. Reviews complete

#195 Add text on Data Explorer disabling
  platform_versioned_docs/version-24.1/data/data-explorer.mdx
Labels: 4. Reviews complete

#197 Fix wrong file name for env file to edit
  platform_versioned_docs/version-24.1/enterprise/data-studios.mdx
Labels: 4. Reviews complete

#201 Redirect to correct latest version
  static/_redirects
Labels: 4. Reviews complete

#194 Data Studios requires Data Explorer
  platform_versioned_docs/version-24.1/data/data-studios.mdx
  platform_versioned_docs/version-24.1/enterprise/data-studios.mdx
Labels: 4. Reviews complete

#188 Add note about AWS Batch 50 queue batch limit
  platform_versioned_docs/version-23.1/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.2/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.3/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.4/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx
Labels: 2. Dev/PM review
