Repository seqeralabs/docs, pull requests merged in 2024-11, with the labels that each got.

#273 Free vs paid usage limits, audit log retention period config
  platform_versioned_docs/version-23.4/enterprise/configuration/configtables/tower_logging.yml
  platform_versioned_docs/version-23.4/limits/limits.mdx
  platform_versioned_docs/version-23.4/monitoring/audit-logs.mdx
  platform_versioned_docs/version-24.1/enterprise/configuration/configtables/tower_logging.yml
  platform_versioned_docs/version-24.1/limits/limits.mdx
  platform_versioned_docs/version-24.1/monitoring/audit-logs.mdx
Labels: 2. Dev/PM review

#284 Fixing products svg
  src/theme/DocSidebar/Desktop/ProductSwitcher/ProductLogo/styles.module.css
  src/theme/DocSidebar/Desktop/ProductSwitcher/images/fusion.dark.svg
  src/theme/DocSidebar/Desktop/ProductSwitcher/images/fusion.svg
  src/theme/DocSidebar/Desktop/ProductSwitcher/images/multiqc.dark.svg
  src/theme/DocSidebar/Desktop/ProductSwitcher/images/nextflow.dark.svg
  src/theme/DocSidebar/Desktop/ProductSwitcher/images/nextflow.svg
  src/theme/DocSidebar/Desktop/ProductSwitcher/images/platform.dark.svg
  src/theme/DocSidebar/Desktop/ProductSwitcher/images/platform.svg
  src/theme/DocSidebar/Desktop/ProductSwitcher/images/wave.dark.svg
  src/theme/DocSidebar/Desktop/ProductSwitcher/images/wave.svg
Labels: 2. Dev/PM review

#281 Add terminal shell syntax highlighting
  docusaurus.config.js
Labels: 4. Reviews complete

#288 Use interactive analysis
  platform_versioned_docs/version-24.1/data_studios/managing.mdx
  platform_versioned_docs/version-24.1/enterprise/docker-compose.mdx
  platform_versioned_docs/version-24.1/enterprise/kubernetes.mdx
  platform_versioned_docs/version-24.1/getting-started/proteinfold.mdx
  platform_versioned_docs/version-24.1/getting-started/quickstart-demo/comm-showcase.mdx
  platform_versioned_docs/version-24.1/getting-started/quickstart-demo/data-studios.mdx
  platform_versioned_docs/version-24.1/getting-started/rnaseq.mdx
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
  platform_versioned_docs/version-24.2/data_studios/managing.mdx
  platform_versioned_docs/version-24.2/enterprise/docker-compose.mdx
  platform_versioned_docs/version-24.2/enterprise/kubernetes.mdx
  platform_versioned_docs/version-24.2/getting-started/proteinfold.mdx
  platform_versioned_docs/version-24.2/getting-started/quickstart-demo/comm-showcase.mdx
  platform_versioned_docs/version-24.2/getting-started/quickstart-demo/data-studios.mdx
  platform_versioned_docs/version-24.2/getting-started/rnaseq.mdx
  platform_versioned_docs/version-24.2/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
Labels: 1. Editor review, 2. Dev/PM review

#272 Corrected commands to mount and trust the certificate on docker compose
  platform_versioned_docs/version-23.3/enterprise/configuration/ssl_tls.mdx
  platform_versioned_docs/version-23.4/enterprise/configuration/ssl_tls.mdx
  platform_versioned_docs/version-24.1/enterprise/configuration/ssl_tls.mdx
Labels: 1. Editor review

#295 Port Nextflow config priority updates to 24.2
  platform_versioned_docs/version-24.2/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-24.2/compute-envs/azure-batch.mdx
  platform_versioned_docs/version-24.2/compute-envs/eks.mdx
  platform_versioned_docs/version-24.2/compute-envs/gke.mdx
  platform_versioned_docs/version-24.2/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-24.2/compute-envs/google-cloud-lifesciences.mdx
  platform_versioned_docs/version-24.2/compute-envs/hpc.mdx
  platform_versioned_docs/version-24.2/compute-envs/k8s.mdx
  platform_versioned_docs/version-24.2/launch/advanced.mdx
Labels: 4. Reviews complete

#312 Add upgrade steps page to v23.4
  platform_versioned_docs/version-23.4/enterprise/upgrade.mdx
  platform_versioned_sidebars/version-23.4-sidebars.json
Labels: 4. Reviews complete

#313 MultiQC v1.25.2
  changelog/multiqc/v1.25.2.mdx
Labels: 4. Reviews complete

#305 Updates and additions to the changelog
  changelog/seqera-cloud/v24.1.0_cycle17.mdx
  changelog/seqera-cloud/v24.2.0_cycle20.mdx
  changelog/seqera-cloud/v24.2.0_cycle21.mdx
  changelog/seqera-cloud/v24.2.0_cycle23.mdx
  changelog/seqera-cloud/v24.2.0_cycle24.mdx
  changelog/seqera-cloud/v24.2.0_cycle25.mdx
  changelog/seqera-cloud/v24.2.0_cycle26.mdx
  changelog/seqera-enterprise/v22.3_major.mdx
  changelog/seqera-enterprise/v22.4_major.mdx
  changelog/seqera-enterprise/v23.1_major.mdx
  changelog/seqera-enterprise/v23.2_major.mdx
  changelog/seqera-enterprise/v23.3_major.mdx
  changelog/seqera-enterprise/v23.4.0.mdx
  changelog/seqera-enterprise/v23.4.4.mdx
  changelog/seqera-enterprise/v23.4.5.mdx
  changelog/seqera-enterprise/v23.4.6.mdx
  changelog/seqera-enterprise/v23.4_major.mdx
  changelog/seqera-enterprise/v24.1.1.mdx
  changelog/seqera-enterprise/v24.1.3.mdx
  changelog/seqera-enterprise/v24.1.4.mdx
  changelog/seqera-enterprise/v24.1.5.mdx
  changelog/seqera-enterprise/v24.1.7.mdx
  changelog/wave_1.12.3.mdx
  changelog/wave_1.12.4.mdx
  platform_versioned_docs/version-24.2/enterprise/release_notes/enterprise_latest.mdx
  platform_versioned_sidebars/version-24.2-sidebars.json
Labels: 4. Reviews complete
