Repository seqeralabs/docs, pull requests merged in 2024-10, with the labels that each got.

#242 Fix "local workspace" wording
  platform_versioned_docs/version-23.4/orgs-and-teams/workspace-management.mdx
  platform_versioned_docs/version-24.1/orgs-and-teams/workspace-management.mdx
Labels: 2. Dev/PM review

#253 Adding Link to Batch Setup
  platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx
Labels: 4. Reviews complete

#256 Update proxy.yml
  platform_versioned_docs/version-24.1/enterprise/_templates/k8s/data_studios/proxy.yml
Labels: 4. Reviews complete

#243 Added missing link to AWS quotas page
  platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx
Labels: 1. Editor review

#262 Minor update to clarify how GCP Batch Behaves
  platform_versioned_docs/version-24.1/compute-envs/google-cloud-batch.mdx
Labels: 4. Reviews complete

#234 Switched final line position
  platform_versioned_docs/version-24.1/limits/limits.mdx
Labels: 1. Editor review

#251 Add steps for manually creating API secret
  platform_versioned_docs/version-24.1/compute-envs/k8s.mdx
Labels: 4. Reviews complete

#191 New structure for FAQs
  changelog/wave_1.12.3.mdx
  changelog/wave_1.12.4.mdx
  platform_versioned_docs/version-22.4/faqs.mdx
  platform_versioned_docs/version-24.1/data/data-studios.mdx
  platform_versioned_docs/version-24.1/faqs.mdx
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/_images/data_studios_notebook_fusion.png
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/api_and_cli.mdx
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/aws_troubleshooting.mdx
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/azure_troubleshooting.mdx
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/datasets_troubleshooting.mdx
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/nextflow.mdx
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/troubleshooting.mdx
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/workspaces_troubleshooting.mdx
  platform_versioned_sidebars/version-24.1-sidebars.json
  static/_redirects
Labels: 4. Reviews complete

#265 Update dashboard.mdx
  platform_versioned_docs/version-24.1/monitoring/dashboard.mdx
Labels: 2. Dev/PM review

#268 BT-125 Add robots.txt file for Atlassian AI scrapping
  static/robots.txt
Labels: 4. Reviews complete

#270 Update dashboard.mdx
  platform_versioned_docs/version-24.1/monitoring/dashboard.mdx
Labels: 2. Dev/PM review
