Repository seqeralabs/docs, pull requests merged in 2024-05, with the labels that each got.

#26 skeleton for data studio checkpoints
  platform_versioned_docs/version-23.4.0/data/data-studios.mdx
Labels: do not merge, boston-2024

#46 Add Data Studio 5G overlay file system limit
  platform_versioned_docs/version-23.4.0/data/data-studios.mdx
Labels: boston-2024

#31 Custom App name for SSM config
  platform_versioned_docs/version-23.3.0/enterprise/_templates/docker/tower.yml
  platform_versioned_docs/version-23.3.0/enterprise/_templates/k8s/configmap.yml
  platform_versioned_docs/version-23.3.0/enterprise/configuration/aws_parameter_store.mdx
  platform_versioned_docs/version-23.3.0/enterprise/configuration/overview.mdx
  platform_versioned_docs/version-23.4.0/enterprise/_templates/docker/tower.yml
  platform_versioned_docs/version-23.4.0/enterprise/_templates/k8s/configmap.yml
  platform_versioned_docs/version-23.4.0/enterprise/configuration/aws_parameter_store.mdx
  platform_versioned_docs/version-23.4.0/enterprise/configuration/overview.mdx
Labels: 2. Dev/PM review

#56 Update Platform / Nextflow base versions
  platform_versioned_docs/version-23.4.0/functionality_matrix/functionality_matrix.mdx
Labels: 4. Reviews complete

#55 Clarify default permissions, and stopping in aws console
  platform_versioned_docs/version-23.4.0/data/data-studios.mdx
Labels: 2. Dev/PM review

#50 Kubernetes deployment page updates
  platform_versioned_docs/version-23.3.0/enterprise/kubernetes.mdx
  platform_versioned_docs/version-23.4.0/enterprise/kubernetes.mdx
Labels: 4. Reviews complete

#63 Fix internal link casualties
  platform_versioned_docs/version-23.3.0/enterprise/advanced-topics/manual-aws-batch-setup.mdx
  platform_versioned_docs/version-23.3.0/launch/cache-resume.mdx
  platform_versioned_docs/version-23.4.0/enterprise/advanced-topics/manual-aws-batch-setup.mdx
  platform_versioned_docs/version-23.4.0/launch/cache-resume.mdx
Labels: 4. Reviews complete

#52 Add words to Vale allow list
  .github/styles/config/vocabularies/Seqera/accept.txt
Labels: 4. Reviews complete

#53 Update README for Wave Git submodule use
  README.md
Labels: 4. Reviews complete

#10 Data Explorer: Generate download script
  platform_versioned_docs/version-23.4.0/data/data-explorer.mdx
Labels: 4. Reviews complete

#60 Pre-Boston clean-up and move to Public Preview
  platform_versioned_docs/version-23.4.0/data/data-studios.mdx
  platform_versioned_sidebars/version-23.4.0-sidebars.json
Labels: 4. Reviews complete, boston-2024

#67 Navbar - tweak wording for product
  src/theme/Navbar/Layout/SeqeraHeader/HeaderDesktop/Submenu/Products/index.jsx
  src/theme/Navbar/Layout/SeqeraHeader/HeaderDesktop/Submenu/Products/styles.module.css
Labels: 4. Reviews complete

#62 Enable GitHub editing for Wave
  docusaurus.config.js
Labels: 4. Reviews complete

#73 Add links between doc sets to README
  README.md
Labels: 4. Reviews complete
