Repository seqeralabs/docs, pull requests merged in 2024-12, with the labels that each got.

#283 Remove references to `redisson.*` properties
  platform_versioned_docs/version-23.3/enterprise/configuration/configtables/db_aws.yml
  platform_versioned_docs/version-23.3/enterprise/configuration/configtables/db_yml.yml
  platform_versioned_docs/version-23.4/enterprise/configuration/configtables/db_aws.yml
  platform_versioned_docs/version-23.4/enterprise/configuration/configtables/db_yml.yml
  platform_versioned_docs/version-24.1/enterprise/configuration/configtables/db_aws.yml
  platform_versioned_docs/version-24.1/enterprise/configuration/configtables/db_yml.yml
  platform_versioned_docs/version-24.2/enterprise/configuration/configtables/db_aws.yml
  platform_versioned_docs/version-24.2/enterprise/configuration/configtables/db_yml.yml
Labels: 1. Editor review, 2. Dev/PM review

#331 Add faster internal link check builds
  .github/workflows/check-internal-links.yml
Labels: 4. Reviews complete

#335 Describe automatic volume resizing in data studios
  platform_versioned_docs/version-24.2/data_studios/index.mdx
  platform_versioned_docs/version-24.2/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
Labels: 4. Reviews complete

#314 Fix DS URL redirect
  static/_redirects
Labels: 4. Reviews complete

#309 Describe Data Studios template image versioning
  platform_versioned_docs/version-24.2/data_studios/index.mdx
Labels: 4. Reviews complete

#338 [Fusion] Add Fusion Snapshots docs
  fusion_docs/guide/snapshots.mdx
Labels: 4. Reviews complete

#342 PLAT-1057: Fix DS custom env YAML example
  platform_versioned_docs/version-24.1/data_studios/custom-envs.mdx
  platform_versioned_docs/version-24.2/data_studios/custom-envs.mdx
Labels: 2. Dev/PM review

#343 PLAT-1059: Redis 6.2 is required for Enterprise
  platform_versioned_docs/version-24.2/enterprise/configuration/overview.mdx
Labels: 4. Reviews complete

#349 Upgrade to latest Docusaurus 3.6.3 release
  package-lock.json
  package.json
Labels: Reviews complete

#347 [Data Studios] Revising capitalization
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
  platform_versioned_docs/version-24.2/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
Labels: Reviews complete

#357 ENT 24.2 container image URLs (pending release)
  platform_versioned_docs/version-24.2/enterprise/_templates/cloudformation/aws-ecs-cloudformation.json
  platform_versioned_docs/version-24.2/enterprise/_templates/docker/docker-compose.yml
  platform_versioned_docs/version-24.2/enterprise/_templates/k8s/tower-cron.yml
  platform_versioned_docs/version-24.2/enterprise/_templates/k8s/tower-svc.yml
  platform_versioned_docs/version-24.2/enterprise/index.mdx
  platform_versioned_docs/version-24.2/enterprise/kubernetes.mdx
  platform_versioned_docs/version-24.2/enterprise/prerequisites/aws.mdx
  platform_versioned_docs/version-24.2/enterprise/prerequisites/azure.mdx
  platform_versioned_docs/version-24.2/enterprise/prerequisites/gcp.mdx
  platform_versioned_docs/version-24.2/enterprise/prerequisites/on-prem.mdx
Labels: enterprise-release-24.2

#344 EDU-427: Add Data Studios events to audit log table
  platform_versioned_docs/version-24.2/monitoring/audit-logs.mdx
  platform_versioned_docs/version-24.2/monitoring/configtables/log_events.yml
Labels: Dev/PM review, enterprise-release-24.2

#341 [EDU-421] 24.2 Changelog
  changelog/seqera-enterprise/v22.3.mdx
  changelog/seqera-enterprise/v22.4.mdx
  changelog/seqera-enterprise/v23.1.mdx
  changelog/seqera-enterprise/v23.2.mdx
  changelog/seqera-enterprise/v23.3.mdx
  changelog/seqera-enterprise/v23.4.mdx
  changelog/seqera-enterprise/v24.1.mdx
  changelog/seqera-enterprise/v24.2.mdx
Labels: Editor review, Dev/PM review, enterprise-release-24.2

#333 Add limitation regarding EFS file system
  platform_versioned_docs/version-24.2/data_studios/index.mdx
Labels: Reviews complete, enterprise-release-24.2

#345 Document limitations of config profiles detection for dropdown
  platform_versioned_docs/version-24.2/launch/launchpad.mdx
Labels: enterprise-release-24.2

#355 Enterprise 24.2: Amazon Linux2023 AMI admonition update
  platform_versioned_docs/version-24.2/compute-envs/aws-batch.mdx
Labels: Reviews complete, enterprise-release-24.2

#354 [EDU-426] Enterprise 24.2: Launch form config update
  platform_versioned_docs/version-24.2/enterprise/configuration/configtables/features_env.yml
  platform_versioned_docs/version-24.2/enterprise/upgrade.mdx
  platform_versioned_docs/version-24.2/launch/launchpad.mdx
Labels: Dev/PM review, enterprise-release-24.2

#336 [Platform] Update redirects with new entry: CLI docs
  static/_redirects
Labels: 1. Editor review

#362 Fixing codeblock component
  src/css/main.css
Labels: 1. Reviews complete

#361 Renamed 23.4 file for consistency
  changelog/seqera-enterprise/v23.4.mdx
Labels: 1. Editor review
