Repository seqeralabs/docs, pull requests merged in 2024-09, with the labels that each got.

#179 [24.2] Update resource labels docs to mention tag propagation to volumes
  platform_versioned_docs/version-24.1/resource-labels/overview.mdx
Labels: 4. Reviews complete

#129 Port and update CLI docs
  platform_versioned_docs/version-23.4/api/overview.mdx
  platform_versioned_docs/version-23.4/cli/_images/tw-info.jpg
  platform_versioned_docs/version-23.4/cli/_images/tw-screenshot.png
  platform_versioned_docs/version-23.4/cli/cli.mdx
  platform_versioned_docs/version-23.4/cli/commands.mdx
  platform_versioned_docs/version-23.4/cli/installation.mdx
  platform_versioned_docs/version-23.4/cli/overview.mdx
  platform_versioned_docs/version-23.4/getting-started/deployment-options.mdx
  platform_versioned_docs/version-23.4/getting-started/quickstart-demo/automation.mdx
  platform_versioned_docs/version-23.4/pipeline-actions/overview.mdx
  platform_versioned_docs/version-24.1/api/overview.mdx
  platform_versioned_docs/version-24.1/cli/_images/tw-info.jpg
  platform_versioned_docs/version-24.1/cli/_images/tw-screenshot.png
  platform_versioned_docs/version-24.1/cli/cli.mdx
  platform_versioned_docs/version-24.1/cli/commands.mdx
  platform_versioned_docs/version-24.1/cli/installation.mdx
  platform_versioned_docs/version-24.1/cli/overview.mdx
  platform_versioned_docs/version-24.1/getting-started/deployment-options.mdx
  platform_versioned_docs/version-24.1/getting-started/quickstart-demo/automation.mdx
  platform_versioned_docs/version-24.1/pipeline-actions/overview.mdx
  platform_versioned_sidebars/version-23.4-sidebars.json
  platform_versioned_sidebars/version-24.1-sidebars.json
Labels: 4. Reviews complete

#193 Cloud release 24.2.0 - 28 August 2024
  platform_versioned_docs/version-24.1/cloud/changelog.mdx
Labels: 2. Dev/PM review

#203 Upgrade to Docusaurus v3.5.2
  package-lock.json
  package.json
Labels: 1. Editor review, 2. Dev/PM review

#207 Platform docs IA update
  platform_versioned_docs/version-23.4/enterprise/general_troubleshooting.mdx
  platform_versioned_docs/version-23.4/faqs.mdx
  platform_versioned_docs/version-23.4/functionality_matrix/functionality_matrix.mdx
  platform_versioned_docs/version-23.4/launch/launchpad.mdx
  platform_versioned_docs/version-24.1/enterprise/general_troubleshooting.mdx
  platform_versioned_docs/version-24.1/faqs.mdx
  platform_versioned_docs/version-24.1/functionality_matrix/functionality_matrix.mdx
  platform_versioned_docs/version-24.1/launch/launchpad.mdx
  platform_versioned_sidebars/version-23.4-sidebars.json
  platform_versioned_sidebars/version-24.1-sidebars.json
Labels: 4. Reviews complete

#214 Adjust spacing for lists
  src/css/misc.css
Labels: 4. Reviews complete

#215 Added correction to the Firewall configuration page
  platform_versioned_docs/version-23.3/enterprise/advanced-topics/firewall-configuration.mdx
  platform_versioned_docs/version-23.4/enterprise/advanced-topics/firewall-configuration.mdx
  platform_versioned_docs/version-24.1/enterprise/advanced-topics/firewall-configuration.mdx
Labels: 1. Editor review

#208 Add redirects for Wave documentation URL changes
  static/_redirects
Labels: 4. Reviews complete

#217 Change http to https
  src/theme/Navbar/Layout/SeqeraHeader/HeaderDesktop/NavItems/index.jsx
  src/theme/Navbar/Layout/SeqeraHeader/HeaderDesktop/Submenu/Resources/index.jsx
Labels: 3. UX review

#219 Omit service that no longer exists for Docker
  platform_versioned_docs/version-24.1/enterprise/docker-compose.mdx
Labels: 4. Reviews complete

#226 Enterprise 24.1.5 release docs — image URLs, matrix, and changelog
  platform_versioned_docs/version-23.4/monitoring/cloud-costs.mdx
  platform_versioned_docs/version-24.1/data/data-studios.mdx
  platform_versioned_docs/version-24.1/enterprise/_templates/cloudformation/aws-ecs-cloudformation.json
  platform_versioned_docs/version-24.1/enterprise/_templates/docker/docker-compose.yml
  platform_versioned_docs/version-24.1/enterprise/_templates/k8s/ingress.eks.yml
  platform_versioned_docs/version-24.1/enterprise/_templates/k8s/tower-cron.yml
  platform_versioned_docs/version-24.1/enterprise/_templates/k8s/tower-svc.yml
  platform_versioned_docs/version-24.1/enterprise/docker-compose.mdx
  platform_versioned_docs/version-24.1/enterprise/index.mdx
  platform_versioned_docs/version-24.1/enterprise/kubernetes.mdx
  platform_versioned_docs/version-24.1/enterprise/prerequisites/aws.mdx
  platform_versioned_docs/version-24.1/enterprise/prerequisites/azure.mdx
  platform_versioned_docs/version-24.1/enterprise/prerequisites/gcp.mdx
  platform_versioned_docs/version-24.1/enterprise/prerequisites/on-prem.mdx
  platform_versioned_docs/version-24.1/enterprise/release_notes/enterprise_changelog.mdx
  platform_versioned_docs/version-24.1/functionality_matrix/functionality_matrix.mdx
  platform_versioned_docs/version-24.1/monitoring/cloud-costs.mdx
  platform_versioned_sidebars/version-23.4-sidebars.json
  platform_versioned_sidebars/version-24.1-sidebars.json
Labels: 1. Editor review, 2. Dev/PM review

#202 Improve API overview
  platform_versioned_docs/version-23.4/api/_images/api_example_call.png
  platform_versioned_docs/version-23.4/api/overview.mdx
  platform_versioned_docs/version-24.1/api/_images/api_example_call.png
  platform_versioned_docs/version-24.1/api/overview.mdx
  src/components/Button/index.tsx
  src/components/Button/index_old.tsx
  src/components/Button/styles.module.css
  src/theme/MDXComponents.js
Labels: 1. Editor review, 2. Dev/PM review

#173 Platform Fusion docs overhaul
  fusion_docs/index.mdx
  platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-24.1/compute-envs/azure-batch.mdx
  platform_versioned_docs/version-24.1/compute-envs/eks.mdx
  platform_versioned_docs/version-24.1/compute-envs/gke.mdx
  platform_versioned_docs/version-24.1/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-24.1/supported_software/fusion/fusion.mdx
Labels: 1. Editor review, 2. Dev/PM review

#210 Minor typo in use dataset section
  platform_versioned_docs/version-22.4/datasets/overview.mdx
  platform_versioned_docs/version-23.1/datasets/overview.mdx
  platform_versioned_docs/version-23.2/datasets/overview.mdx
  platform_versioned_docs/version-23.3/data/datasets.mdx
  platform_versioned_docs/version-23.4/data/datasets.mdx
  platform_versioned_docs/version-24.1/data/datasets.mdx
Labels: 4. Reviews complete

#224 Remove extraneous trailing spaces
  platform_versioned_sidebars/version-23.2-sidebars.json
  platform_versioned_sidebars/version-23.3-sidebars.json
  platform_versioned_sidebars/version-23.4-sidebars.json
  platform_versioned_sidebars/version-24.1-sidebars.json
Labels: 4. Reviews complete

#225 Ignore domain that does not resolve any longer
  lychee.toml
Labels: 4. Reviews complete

#190 Update pipeline optimization K8s deployment steps
  platform_versioned_docs/version-23.3/enterprise/configuration/pipeline_optimization.mdx
  platform_versioned_docs/version-23.4/enterprise/configuration/pipeline_optimization.mdx
  platform_versioned_docs/version-24.1/enterprise/_templates/k8s/configmap.yml
  platform_versioned_docs/version-24.1/enterprise/configuration/pipeline_optimization.mdx
Labels: 1. Editor review, 2. Dev/PM review

#232 Add running data studios default limit
  platform_versioned_docs/version-24.1/limits/limits.mdx
Labels: 4. Reviews complete

#239 Update data-studios.mdx
  platform_versioned_docs/version-24.1/enterprise/data-studios.mdx
Labels: 1. Editor review
