Repository seqeralabs/docs, pull requests merged in 2024-07, with the labels that each got.

#106 Removed Graviton3 reference in 23.3 documentation
  platform_versioned_docs/version-23.3.0/compute-envs/aws-batch.mdx
Labels: 4. Reviews complete

#70 Remove outdated AWS docs link (no replacement)
  platform_versioned_docs/version-23.3.0/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.4.0/compute-envs/aws-batch.mdx
Labels: 2. Dev/PM review

#107 Update data privacy task metadata attempts column description
  platform_versioned_docs/version-22.4.0/data-privacy/overview.mdx
  platform_versioned_docs/version-23.1.0/data-privacy/overview.mdx
  platform_versioned_docs/version-23.2.0/data-privacy/overview.mdx
  platform_versioned_docs/version-23.3.0/data-privacy/overview.mdx
  platform_versioned_docs/version-23.4.0/data-privacy/overview.mdx
  platform_versioned_docs/version-24.1.1/data-privacy/overview.mdx
Labels: 4. Reviews complete

#15 Update default env var for DE
  platform_versioned_docs/version-23.4.0/data/data-explorer.mdx
  platform_versioned_docs/version-24.1.1/data/data-explorer.mdx
Labels: 1. Editor review, 2. Dev/PM review
