Repository seqeralabs/docs, pull requests merged in 2025-01, with the labels that each got.

#368 Changelog: MultiQC 1.26
  changelog/multiqc/v1.26.mdx
Labels: 1. Reviews complete

#367 Nav layout issue
  src/css/main.css
Labels: 1. Dev/PM review

#382 Apply npm audit changes
  package-lock.json
  package.json
Labels: 1. Reviews complete

#375 PLAT-997: Add EFS limitation
  platform_versioned_docs/version-24.1/data_studios/index.mdx
Labels: 1. Editor review, 1. Dev/PM review

#377 Update Data Explorer AWS policies
  platform_versioned_docs/version-24.2/compute-envs/aws-batch.mdx
Labels: 1. Reviews complete, enterprise-release-24.2

#388 Drop unnecessary name field from env file
  platform_versioned_docs/version-24.1/data_studios/custom-envs.mdx
  platform_versioned_docs/version-24.2/data_studios/custom-envs.mdx
Labels: enterprise-release-24.2, enterprise-release-24.1

#366 [EDU-440] EFS volume mounting content update
  changelog/seqera-enterprise/v24.2.mdx
  platform_versioned_docs/version-24.2/data_studios/index.mdx
Labels: 1. Dev/PM review, enterprise-release-24.2

#389 Cookie banner
  package-lock.json
  package.json
  platform_versioned_docs/version-23.4/api/overview.mdx
  platform_versioned_docs/version-24.1/api/overview.mdx
  platform_versioned_docs/version-24.2/api/overview.mdx
  src/components/Button/Arrow.tsx
  src/components/Button/arrow.inline.svg
  src/components/Button/index.tsx
  src/components/Button/styles.module.css
  src/css/components/checklist.css
  src/css/theme-colors.css
  src/modules/Homepage/index.tsx
  src/modules/Homepage/styles.module.css
  src/theme/Layout/CookieBanner/Cookie.tsx
  src/theme/Layout/CookieBanner/index.tsx
  src/theme/Layout/CookieBanner/styles.module.css
  src/theme/Layout/index.js
  src/typings.d.ts
  tailwind.config.js
Labels: 1. Dev/PM review

#393 Upgrade to latest Dinosaur
  package-lock.json
  package.json
Labels: 1. Reviews complete

#398 Clarify Data Studios GPU and CPU availability
  changelog/seqera-enterprise/v24.2.mdx
Labels: enterprise-release-24.2

#330 Add steps to handle Azure MySQL foreign keys
  changelog/seqera-enterprise/v23.3.mdx
  changelog/seqera-enterprise/v23.4.mdx
  changelog/seqera-enterprise/v24.2.mdx
  platform_versioned_docs/version-23.3/enterprise/release_notes/enterprise_latest.mdx
  platform_versioned_docs/version-24.2/enterprise/prerequisites/azure.mdx
Labels: enterprise-release-24.2, enterprise-release-24.1

#395 24.2.0_cycle28 - changelog
  changelog/seqera-cloud/v24.2.0_cycle28.mdx
  changelog/seqera-enterprise/v24.2.3.mdx
  platform_versioned_docs/version-24.2/enterprise/_templates/cloudformation/aws-ecs-cloudformation.json
  platform_versioned_docs/version-24.2/enterprise/_templates/docker/docker-compose.yml
  platform_versioned_docs/version-24.2/enterprise/_templates/k8s/tower-cron.yml
  platform_versioned_docs/version-24.2/enterprise/_templates/k8s/tower-svc.yml
  platform_versioned_docs/version-24.2/enterprise/index.mdx
  platform_versioned_docs/version-24.2/enterprise/kubernetes.mdx
  platform_versioned_docs/version-24.2/enterprise/prerequisites/aws.mdx
  platform_versioned_docs/version-24.2/enterprise/prerequisites/azure.mdx
  platform_versioned_docs/version-24.2/enterprise/prerequisites/gcp.mdx
  platform_versioned_docs/version-24.2/enterprise/prerequisites/on-prem.mdx
Labels: 1. Editor review, 1. Dev/PM review

#402 Fix link anchor for UI code
  platform_versioned_docs/version-23.4/data/data-explorer.mdx
  platform_versioned_docs/version-24.1/data/data-explorer.mdx
  platform_versioned_docs/version-24.2/data/data-explorer.mdx
Labels: 1. Reviews complete

#408 Github Actions / Webhooks for Algolia
  .github/workflows/algolia-index.yml
  scripts/indexDocs.js
Labels: 1. Dev/PM review
