Repository seqeralabs/docs, pull requests merged in 2025-04, with the labels that each got.

#533 Add unpublished tag to Data Studios docs
  platform_versioned_docs/version-23.3/data/data-studios.mdx
Labels: 1. Editor review

#539 Correction of "data-link" in Studios docs
  platform_versioned_docs/version-25.1/studios/managing.mdx
Labels: 3. Reviews complete

#550 Removed mdx from Wave link
  platform-cloud/docs/studios/custom-envs.mdx
Labels: 1. Editor review

#555 [Ent] 25.1.1 release notes
  changelog/seqera-enterprise/v25.1.1.mdx
  changelog/seqera-enterprise/v25.1.mdx
  platform-enterprise_versioned_docs/version-25.1/enterprise/_templates/docker/docker-compose.yml
  platform-enterprise_versioned_docs/version-25.1/enterprise/_templates/k8s/tower-cron.yml
  platform-enterprise_versioned_docs/version-25.1/enterprise/_templates/k8s/tower-svc.yml
  platform-enterprise_versioned_docs/version-25.1/enterprise/index.mdx
  platform-enterprise_versioned_docs/version-25.1/enterprise/kubernetes.mdx
  platform-enterprise_versioned_docs/version-25.1/enterprise/prerequisites/aws.mdx
  platform-enterprise_versioned_docs/version-25.1/enterprise/prerequisites/azure.mdx
  platform-enterprise_versioned_docs/version-25.1/enterprise/prerequisites/gcp.mdx
  platform-enterprise_versioned_docs/version-25.1/enterprise/prerequisites/on-prem.mdx
  platform-enterprise_versioned_docs/version-25.1/studios/managing.mdx
Labels: 1. Editor review, 1. Dev/PM/SME

#561 Changelog for Seqera Cloud cycle 7
  changelog/seqera-cloud/25.1.0_cycle7.mdx
Labels: 3. Reviews complete, cloud release

#567 A caveat at the bottom of the Cloud compute environment page...
  platform-cloud/docs/compute-envs/aws-batch.mdx
Labels: 3. Reviews complete

#547 [EDU-670] Add snapshots to Fusion reference
  fusion_docs/reference.mdx
Labels: 3. Reviews complete, cloud release

#565 Add snapshots content to Fusion User Guide
  fusion_docs/guide/snapshots.mdx
  fusion_docs/sidebar.json
Labels: 1. Dev/PM/SME

#569 Update to AWS Batch page (caveat)
  platform-cloud/docs/compute-envs/aws-batch.mdx
  platform-enterprise_versioned_docs/version-25.1/compute-envs/aws-batch.mdx
Labels: 1. Editor review

#564 Changelog v25.1.0_cycle9.mdx
  changelog/seqera-cloud/v25.1.0_cycle9.mdx
  platform-cloud/docs/compute-envs/aws-batch.mdx
Labels: cloud release

#563 Cloud release notes - cycle8 and cycle9
  changelog/seqera-cloud/v25.0.1_cycle8.mdx
  changelog/seqera-cloud/v25.1.0_cycle9.mdx
  platform-cloud/docs/compute-envs/aws-batch.mdx
Labels: 3. Reviews complete, cloud release
