Repository seqeralabs/docs, pull requests merged in 2025-06, with the labels that each got.

#651 Improve pipeline icon upload instructions to include order of priority
  changelog/seqera-enterprise/v25.1.md
  platform-cloud/docs/getting-started/quickstart-demo/add-pipelines.md
  platform-enterprise_versioned_docs/version-23.2/getting-started/community-showcase.md
  platform-enterprise_versioned_docs/version-23.3/getting-started/community-showcase.md
  platform-enterprise_versioned_docs/version-24.1/getting-started/quickstart-demo/add-data.md
  platform-enterprise_versioned_docs/version-24.1/getting-started/quickstart-demo/add-pipelines.md
  platform-enterprise_versioned_docs/version-24.1/getting-started/quickstart-demo/automation.md
  platform-enterprise_versioned_docs/version-24.1/getting-started/quickstart-demo/comm-showcase.mdx
  platform-enterprise_versioned_docs/version-24.1/getting-started/quickstart-demo/data-studios.md
  platform-enterprise_versioned_docs/version-24.1/getting-started/quickstart-demo/launch-pipelines.md
  platform-enterprise_versioned_docs/version-24.1/getting-started/quickstart-demo/monitor-runs.md
  platform-enterprise_versioned_docs/version-24.1/getting-started/quickstart-demo/pipeline-optimization.md
  platform-enterprise_versioned_docs/version-24.1/getting-started/quickstart-demo/view-run-information.md
  platform-enterprise_versioned_docs/version-24.2/getting-started/quickstart-demo/add-data.md
  platform-enterprise_versioned_docs/version-24.2/getting-started/quickstart-demo/add-pipelines.md
  platform-enterprise_versioned_docs/version-24.2/getting-started/quickstart-demo/automation.md
  platform-enterprise_versioned_docs/version-24.2/getting-started/quickstart-demo/comm-showcase.mdx
  platform-enterprise_versioned_docs/version-24.2/getting-started/quickstart-demo/data-studios.md
  platform-enterprise_versioned_docs/version-24.2/getting-started/quickstart-demo/launch-pipelines.md
  platform-enterprise_versioned_docs/version-24.2/getting-started/quickstart-demo/monitor-runs.md
  platform-enterprise_versioned_docs/version-24.2/getting-started/quickstart-demo/pipeline-optimization.md
  platform-enterprise_versioned_docs/version-24.2/getting-started/quickstart-demo/view-run-information.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/quickstart-demo/add-pipelines.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/quickstart-demo/comm-showcase.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/quickstart-demo/monitor-runs.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/quickstart-demo/pipeline-optimization.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/quickstart-demo/studios.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/quickstart-demo/view-run-information.md
  platform-enterprise_versioned_sidebars/version-23.1-sidebars.json
  platform-enterprise_versioned_sidebars/version-23.2-sidebars.json
  platform-enterprise_versioned_sidebars/version-23.3-sidebars.json
Labels: 3. Reviews complete

#650 Add system-dependence information for timezones
  platform-cloud/docs/getting-started/deployment-options.md
  platform-cloud/docs/getting-started/overview.md
  platform-cloud/docs/getting-started/proteinfold.md
  platform-cloud/docs/getting-started/quickstart-demo/add-data.md
  platform-cloud/docs/getting-started/quickstart-demo/automation.md
  platform-cloud/docs/getting-started/quickstart-demo/comm-showcase.md
  platform-cloud/docs/getting-started/quickstart-demo/monitor-runs.md
  platform-cloud/docs/getting-started/quickstart-demo/pipeline-optimization.md
  platform-cloud/docs/getting-started/quickstart-demo/studios.md
  platform-cloud/docs/getting-started/quickstart-demo/view-run-information.md
  platform-cloud/docs/getting-started/rnaseq.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/deployment-options.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/proteinfold.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/quickstart-demo/add-data.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/quickstart-demo/pipeline-optimization.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/quickstart-demo/studios.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/quickstart-demo/view-run-information.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/rnaseq.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/studios.md
Labels: 1. Editor review

#638 Update rehype-katex version
  package-lock.json
  package.json
Labels: 1. Editor review, 1. Dev/PM/SME

#657 Fix back to docs for cloud and enterprise
  src/theme/BlogSidebar/Desktop/index.js
Labels: 3. Reviews complete

#611 Update fetch oss to include branch
  internal/fetch-docs-oss.mjs
Labels: 3. Reviews complete

#662 Add note for wave for public ecr images
  platform-cloud/docs/credentials/aws_registry_credentials.md
  platform-enterprise_versioned_docs/version-23.3/credentials/aws_registry_credentials.md
  platform-enterprise_versioned_docs/version-23.4/credentials/aws_registry_credentials.md
  platform-enterprise_versioned_docs/version-24.1/credentials/aws_registry_credentials.md
  platform-enterprise_versioned_docs/version-24.2/credentials/aws_registry_credentials.md
  platform-enterprise_versioned_docs/version-25.1/credentials/aws_registry_credentials.md
Labels: 3. Reviews complete

#663 Update RStudios to R-IDE
  platform-cloud/docs/getting-started/quickstart-demo/comm-showcase.md
  platform-cloud/docs/getting-started/quickstart-demo/studios.md
  platform-cloud/docs/getting-started/studios.md
  platform-cloud/docs/studios/custom-envs.md
  platform-cloud/docs/studios/managing.md
  platform-cloud/docs/studios/overview.md
  platform-enterprise_versioned_docs/version-24.1/data_studios/overview.md
  platform-enterprise_versioned_docs/version-24.1/enterprise/data-studios.md
  platform-enterprise_versioned_docs/version-24.1/getting-started/proteinfold.mdx
  platform-enterprise_versioned_docs/version-24.1/getting-started/quickstart-demo/data-studios.md
  platform-enterprise_versioned_docs/version-24.1/getting-started/rnaseq.mdx
  platform-enterprise_versioned_docs/version-24.2/data_studios/overview.md
  platform-enterprise_versioned_docs/version-24.2/enterprise/studios.md
  platform-enterprise_versioned_docs/version-24.2/troubleshooting_and_faqs/data_studios_troubleshooting.md
  platform-enterprise_versioned_docs/version-25.1/enterprise/studios.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/proteinfold.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/quickstart-demo/studios.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/rnaseq.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/studios.md
  platform-enterprise_versioned_docs/version-25.1/studios/managing.md
  platform-enterprise_versioned_docs/version-25.1/studios/overview.md
  platform-enterprise_versioned_docs/version-25.1/troubleshooting_and_faqs/studios_troubleshooting.md
Labels: 1. Editor review, 1. Dev/PM/SME

#683 [Ent 25.2] Data explorer multiple file upload
  platform-enterprise_versioned_docs/version-25.2/data/data-explorer.md
Labels: 1. Dev/PM/SME
