Repository seqeralabs/docs, pull requests merged in 2025-03, with the labels that each got.

#491 EDU-438: Add env vars to Studios enterprise docs
  platform_versioned_docs/version-24.2/enterprise/configuration/configtables/data_features_env.yml
Labels: 3. Reviews complete

#489 [Cloud] Create v24.3.0_cycle4.mdx
  changelog/seqera-cloud/v24.3.0-cycle3.mdx
  changelog/seqera-cloud/v24.3.0_cycle4.mdx
Labels: 1. Dev/PM/SME, do not merge, cloud release

#507 [Chore] New section on migrating Studios
  platform_versioned_docs/version-24.3/studios/managing.mdx
Labels: 3. Reviews complete

#511 Troubleshooting failed custom envs - cache vs. fresh pull
  platform_versioned_docs/version-24.3/troubleshooting_and_faqs/studios_troubleshooting.mdx
Labels: 3. Reviews complete

#514 Update AWS Batch min CPUs warning
  platform_versioned_docs/version-22.4/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.1/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.2/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.3/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.4/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-24.2/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-24.3/compute-envs/aws-batch.mdx
Labels: 3. Reviews complete

#520 [Studios] Add Privacy
  platform_versioned_docs/version-24.3/studios/managing.mdx
Labels: 1. Dev/PM/SME

#525 [Fix] Link fix for Studios in Enterprise docs
  platform_versioned_docs/version-24.2/enterprise/studios.mdx
Labels: 1. Dev/PM/SME

#531 Revert of a minor test change
  platform_versioned_docs/version-24.3/studios/custom-envs.mdx
Labels: 1. Editor review

#524 Deprecation notice for Google Life Sciences
  platform_versioned_docs/version-23.1/compute-envs/google-cloud-lifesciences.mdx
  platform_versioned_docs/version-23.2/compute-envs/google-cloud-lifesciences.mdx
  platform_versioned_docs/version-23.3/compute-envs/google-cloud-lifesciences.mdx
  platform_versioned_docs/version-23.4/compute-envs/google-cloud-lifesciences.mdx
  platform_versioned_docs/version-24.1/compute-envs/google-cloud-lifesciences.mdx
  platform_versioned_docs/version-24.2/compute-envs/google-cloud-lifesciences.mdx
  platform_versioned_docs/version-24.3/compute-envs/google-cloud-lifesciences.mdx
Labels: 1. Dev/PM/SME

#517 Proper capitalization of Spot and On-Demand Instances
  changelog/seqera-enterprise/v24.2.1.mdx
  platform_versioned_docs/version-22.4/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-22.4/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-23.1/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.1/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-23.1/enterprise/advanced-topics/cloudformation.mdx
  platform_versioned_docs/version-23.2/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.2/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-23.2/enterprise/advanced-topics/cloudformation.mdx
  platform_versioned_docs/version-23.2/enterprise/advanced-topics/manual-aws-batch-setup.mdx
  platform_versioned_docs/version-23.3/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.3/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-23.4/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-23.4/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-23.4/enterprise/advanced-topics/cloudformation.mdx
  platform_versioned_docs/version-23.4/enterprise/advanced-topics/manual-aws-batch-setup.mdx
  platform_versioned_docs/version-23.4/getting-started/rnaseq.mdx
  platform_versioned_docs/version-24.1/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-24.1/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-24.1/enterprise/advanced-topics/manual-aws-batch-setup.mdx
  platform_versioned_docs/version-24.1/getting-started/proteinfold.mdx
  platform_versioned_docs/version-24.1/getting-started/rnaseq.mdx
  platform_versioned_docs/version-24.2/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-24.2/enterprise/advanced-topics/cloudformation.mdx
  platform_versioned_docs/version-24.2/getting-started/proteinfold.mdx
  platform_versioned_docs/version-24.2/getting-started/rnaseq.mdx
  platform_versioned_docs/version-24.3/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-24.3/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-24.3/enterprise/advanced-topics/manual-aws-batch-setup.mdx
  platform_versioned_docs/version-24.3/getting-started/proteinfold.mdx
  platform_versioned_docs/version-24.3/getting-started/rnaseq.mdx
Labels: 3. Reviews complete

#465 [PLAT-1205] Add pipeline image upload instructions
  platform_versioned_docs/version-24.2/getting-started/quickstart-demo/add-pipelines.mdx
  platform_versioned_docs/version-24.2/launch/launchpad.mdx
  platform_versioned_docs/version-24.3/getting-started/quickstart-demo/add-pipelines.mdx
  platform_versioned_docs/version-24.3/launch/launchpad.mdx
  platform_versioned_docs/version-25.1/getting-started/quickstart-demo/add-pipelines.mdx
  platform_versioned_docs/version-25.1/launch/launchpad.mdx
Labels: 1. Editor review

#515 Add Spot Instance section to troubleshooting
  platform_versioned_docs/version-24.1/troubleshooting_and_faqs/nextflow.mdx
  platform_versioned_docs/version-24.2/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-24.2/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-24.2/troubleshooting_and_faqs/nextflow.mdx
  platform_versioned_docs/version-24.3/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-24.3/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-24.3/troubleshooting_and_faqs/nextflow.mdx
  platform_versioned_docs/version-25.1/compute-envs/aws-batch.mdx
  platform_versioned_docs/version-25.1/compute-envs/google-cloud-batch.mdx
  platform_versioned_docs/version-25.1/troubleshooting_and_faqs/nextflow.mdx
Labels: 1. Editor review
