Repository seqeralabs/docs, pull requests merged in 2025-10, with the labels that each got.

#818 [PLAT-1854] docs: Dynamic resource labels
  platform-cloud/docs/orgs-and-teams/roles.md
  platform-cloud/docs/resource-labels/overview.md
Labels: do not merge

#849 [Enterprise] Updated images for enterprise release
  changelog/seqera-enterprise/v25.2.1.md
  changelog/seqera-enterprise/v25.2.2.md
  changelog/seqera-enterprise/v25.2.3.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/_templates/cloudformation/aws-ecs-cloudformation.json
  platform-enterprise_versioned_docs/version-25.2/enterprise/_templates/docker/docker-compose.yml
  platform-enterprise_versioned_docs/version-25.2/enterprise/_templates/k8s/tower-cron.yml
  platform-enterprise_versioned_docs/version-25.2/enterprise/_templates/k8s/tower-svc.yml
  platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/configtables/data_features_env.yml
  platform-enterprise_versioned_docs/version-25.2/enterprise/kubernetes.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/overview.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/prerequisites/aws.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/prerequisites/azure.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/prerequisites/gcp.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/prerequisites/on-prem.md
Labels: 1. Editor review, 1. Dev/PM/SME

#857 Remove reference to env vars in Cloud docs
  platform-cloud/docs/studios/overview.md
Labels: 1. Dev/PM/SME
