Repository seqeralabs/docs, pull requests merged in 2025-07, with the labels that each got.

#679 Docusaurus package update
  package-lock.json
  package.json
Labels: 1. Editor review, 1. Dev/PM/SME

#568 [EDU-685] Update minimum resource requirements for AWS prereqs page
  platform-enterprise_versioned_docs/version-25.1/enterprise/configuration/overview.mdx
  platform-enterprise_versioned_docs/version-25.1/enterprise/prerequisites/aws.mdx
  platform-enterprise_versioned_docs/version-25.1/enterprise/prerequisites/gcp.mdx
Labels: 1. Dev/PM/SME

#688 Add data-links upload and download operations to CLI docs
  platform-cloud/docs/cli/commands.md
  platform-cloud/docs/cli/installation.md
  platform-cloud/docs/resource-labels/overview.md
  platform-enterprise_versioned_docs/version-24.2/getting-started/proteinfold.mdx
  platform-enterprise_versioned_docs/version-25.1/getting-started/proteinfold.mdx
Labels: 3. Reviews complete

#692 [PLAT-2774] Document Launch form URL query parameter support
  platform-enterprise_versioned_docs/version-25.2/launch/launchpad.md
Labels: 3. Reviews complete

#689 Add note about shared Studios sessions
  platform-cloud/docs/orgs-and-teams/workspace-management.md
Labels: 1. Editor review

#686 Roles: Reorganize and fix typo
  platform-cloud/docs/orgs-and-teams/roles.md
Labels: 1. Editor review, 3. Reviews complete

#702 [PLAT-2455] Rename "Pipeline work directory" to "Work directory"
  fusion_docs/guide/aws-eks.md
  fusion_docs/guide/snapshots.md
  platform-cloud/docs/compute-envs/aws-batch.md
  platform-cloud/docs/compute-envs/azure-batch.md
  platform-cloud/docs/compute-envs/eks.md
  platform-cloud/docs/compute-envs/gke.md
  platform-cloud/docs/compute-envs/google-cloud-batch.md
  platform-cloud/docs/compute-envs/seqera-compute.md
  platform-cloud/docs/enterprise/advanced-topics/manual-azure-batch-setup.md
  platform-cloud/docs/getting-started/proteinfold.md
  platform-cloud/docs/getting-started/rnaseq.md
  platform-cloud/docs/getting-started/studios.md
  platform-cloud/docs/studios/overview.md
Labels: 1. Editor review, 1. Dev/PM/SME

#705 [PLAT-3055] Add Wave and Fusion to executor details to run details docs
  platform-cloud/docs/monitoring/run-details.mdx
Labels: 3. Reviews complete

#718 Update licensing.md
  fusion_docs/licensing.md
Labels: 3. Reviews complete

#710 Add Fusion to dashboard
  platform-cloud/cloud-sidebar.json
  platform-cloud/docs/monitoring/dashboard.md
Labels: 1. Editor review, 1. Dev/PM/SME

#732 Update locations in Google Cloud
  platform-cloud/docs/compute-envs/google-cloud.md
Labels: 1. Dev/PM/SME

#726 Add path-based routing and update VSCode version and included libraries
  platform-cloud/docs/studios/overview.md
Labels: 1. Editor review

#738 Release notes - Enterprise
  changelog/seqera-enterprise/v24.1.10.md
  changelog/seqera-enterprise/v24.1.8.md
  changelog/seqera-enterprise/v24.2.6.md
  changelog/seqera-enterprise/v25.1.3.md
Labels: 1. Dev/PM/SME

#727 Update _redirects - Fusion guide
  static/_redirects
Labels: 1. Editor review

#740 Update default Spot price allocation type
  platform-cloud/docs/compute-envs/aws-batch.md
  platform-enterprise_versioned_docs/version-24.2/compute-envs/aws-batch.md
  platform-enterprise_versioned_docs/version-25.1/compute-envs/aws-batch.md
Labels: 1. Editor review

#736 [25.2] Image versions
  platform-enterprise_versioned_docs/version-25.2/enterprise/_templates/cloudformation/aws-ecs-cloudformation.json
  platform-enterprise_versioned_docs/version-25.2/enterprise/_templates/docker/docker-compose.yml
  platform-enterprise_versioned_docs/version-25.2/enterprise/_templates/k8s/tower-cron.yml
  platform-enterprise_versioned_docs/version-25.2/enterprise/_templates/k8s/tower-svc.yml
  platform-enterprise_versioned_docs/version-25.2/enterprise/kubernetes.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/overview.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/prerequisites/aws.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/prerequisites/azure.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/prerequisites/gcp.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/prerequisites/on-prem.md
Labels: 1. Editor review, enterprise-25.2

#748 Update to env vars for 25.2
  platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/aws_parameter_store.md
  platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/configtables/compute_env.yml
  platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/configtables/data_features_env.yml
Labels: enterprise-25.2

#750 Enterprise 25.2 upgrade guidance
  platform-enterprise_versioned_docs/version-25.2/enterprise/upgrade.md
Labels: 1. Dev/PM/SME, enterprise-25.2
