Repository seqeralabs/docs, pull requests merged in 2025-05, with the labels that each got.

#583 AWS Batch doc caveat removes reference to API response
  platform-cloud/docs/compute-envs/aws-batch.mdx
  platform-enterprise_versioned_docs/version-25.1/compute-envs/aws-batch.mdx
Labels: 3. Reviews complete

#596 [PLAT-2092] - Change edit CE to rename CE
  platform-cloud/docs/compute-envs/overview.md
  platform-enterprise_versioned_docs/version-25.1/compute-envs/overview.md
Labels: 3. Reviews complete

#585 Fixed studios image link
  platform-enterprise_versioned_docs/version-24.2/enterprise/studios.md
  platform-enterprise_versioned_docs/version-25.1/enterprise/studios.md
Labels: 3. Reviews complete

#591 Add information on data explorer custom data link value prop and instructions
  platform-cloud/docs/data/data-explorer.md
  platform-enterprise_versioned_docs/version-23.3/data/data-explorer.md
  platform-enterprise_versioned_docs/version-23.4/data/data-explorer.md
  platform-enterprise_versioned_docs/version-24.1/data/data-explorer.md
  platform-enterprise_versioned_docs/version-24.2/data/data-explorer.md
  platform-enterprise_versioned_docs/version-25.1/data/data-explorer.md
Labels: 3. Reviews complete

#608 Removed non-cloud pages from Cloud docs
  platform-cloud/cloud-sidebar.json
  platform-cloud/docs/administration/overview.md
  platform-cloud/docs/monitoring/audit-logs.md
Labels: 3. Reviews complete

#574 [AWS prerequisites] Fixed incorrect formatting for code example
  platform-enterprise_versioned_docs/version-23.1/enterprise/prerequisites/aws.md
Labels: 3. Reviews complete

#581 [PLAT-2252] Document run details page enhancements
  platform-cloud/docs/monitoring/_images/command.png
  platform-cloud/docs/monitoring/_images/configuration.png
  platform-cloud/docs/monitoring/_images/containers.png
  platform-cloud/docs/monitoring/_images/datasets.png
  platform-cloud/docs/monitoring/_images/executor-details.png
  platform-cloud/docs/monitoring/_images/infra-details.png
  platform-cloud/docs/monitoring/_images/interactive-plot.png
  platform-cloud/docs/monitoring/_images/load.png
  platform-cloud/docs/monitoring/_images/metrics-tiles.png
  platform-cloud/docs/monitoring/_images/parameters.png
  platform-cloud/docs/monitoring/_images/progress-bar.png
  platform-cloud/docs/monitoring/_images/reports.png
  platform-cloud/docs/monitoring/_images/run-details.png
  platform-cloud/docs/monitoring/_images/task-details.png
  platform-cloud/docs/monitoring/_images/task-status-tiles.png
  platform-cloud/docs/monitoring/_images/utilization.png
  platform-cloud/docs/monitoring/run-details.md
  platform-cloud/docs/monitoring/run-details.mdx
Labels: 3. Reviews complete

#570 [PLAT-217] Seqera Compute M2 docs
  platform-cloud/cloud-sidebar.json
  platform-cloud/docs/compute-envs/seqera-compute.md
  platform-cloud/docs/limits/limits.md
  platform-cloud/docs/orgs-and-teams/organizations.md
  platform-cloud/docs/orgs-and-teams/workspace-management.md
Labels: do not merge, 3. Reviews complete

#609 AWS Cloud VM
  platform-cloud/cloud-sidebar.json
  platform-cloud/docs/compute-envs/aws-cloud.md
Labels: 3. Reviews complete

#622 Header fix for AWS Cloud
  platform-cloud/docs/compute-envs/aws-cloud.md
Labels: 1. Editor review

#629 Update docs landing page
  src/modules/Homepage/index.tsx
Labels: 1. Editor review

#616 quickwin: update table to emojis for readability
  platform-cloud/docs/orgs-and-teams/roles.md
  platform-enterprise_versioned_docs/version-25.1/orgs-and-teams/roles.md
Labels: 3. Reviews complete

#617 quickwin: Highlight table rows on mouse hover
  src/css/main.css
  src/css/theme-colors.css
Labels: 3. Reviews complete

#577 Update sidebars and remove cloud tutorial
  platform-enterprise_versioned_docs/version-25.1/getting-started/deployment-options.md
  platform-enterprise_versioned_sidebars/version-25.1-sidebars.json
Labels: do not merge, 3. Reviews complete

#634 Index renaming to fix 404s on old Enterprise versions
  platform-enterprise_versioned_docs/version-22.4/platform-enterprise.md
  platform-enterprise_versioned_docs/version-23.1/platform-enterprise.md
  platform-enterprise_versioned_docs/version-23.2/platform-enterprise.md
  platform-enterprise_versioned_docs/version-23.3/platform-enterprise.md
  platform-enterprise_versioned_docs/version-23.4/platform-enterprise.md
  platform-enterprise_versioned_docs/version-24.1/platform-enterprise.md
  platform-enterprise_versioned_sidebars/version-22.4-sidebars.json
  platform-enterprise_versioned_sidebars/version-23.1-sidebars.json
  platform-enterprise_versioned_sidebars/version-23.2-sidebars.json
  platform-enterprise_versioned_sidebars/version-23.3-sidebars.json
  platform-enterprise_versioned_sidebars/version-23.4-sidebars.json
  platform-enterprise_versioned_sidebars/version-24.1-sidebars.json
Labels: 3. Reviews complete

#633 Added Compute and Cloud to list
  platform-cloud/docs/compute-envs/overview.md
Labels: 3. Reviews complete

#620 Add section and link to custom studios examples; update connect-client with a variable
  platform-cloud/docs/studios/custom-envs.md
  platform-enterprise_versioned_docs/version-25.1/studios/custom-envs.md
Labels: 1. Dev/PM/SME, do not merge

#636 Update conda overview and links; update Wave service links
  platform-cloud/docs/studios/custom-envs.md
Labels: do not merge, 3. Reviews complete

#639 EDU-643: adding overrides image-size
  package-lock.json
  package.json
Labels: 1. Dev/PM/SME

#642 FSN-515: Fix EC2 key pair hyperlink
  platform-cloud/docs/compute-envs/aws-cloud.md
Labels: 3. Reviews complete

#643 [Changelog] Create v25.1.0-cycle13_1b294ec.md
  changelog/seqera-cloud/v25.1.0-cycle13_1b294ec.md
Labels: 1. Editor review, 1. Dev/PM/SME

#654 Add minimal editorconfig
  .editorconfig
Labels: 3. Reviews complete
