Repository seqeralabs/docs, pull requests merged in 2025-02, with the labels that each got.

#401 Added errorStrategy breaking change to cloud changelog
  changelog/seqera-cloud/v24.2.0_cycle28.mdx
Labels: 1. Reviews complete

#417 Add studios cli additions and update screenshot
  platform_versioned_docs/version-24.2/cli/_images/tw-info.jpg
  platform_versioned_docs/version-24.2/cli/commands.mdx
Labels: 1. Editor review, 1. Dev/PM review

#419 Apply Data Studios change to tower-svc.yml
  platform_versioned_docs/version-24.1/enterprise/_templates/k8s/tower-cron.yml
  platform_versioned_docs/version-24.1/enterprise/_templates/k8s/tower-svc.yml
  platform_versioned_docs/version-24.1/enterprise/data-studios.mdx
  platform_versioned_docs/version-24.2/enterprise/_templates/k8s/tower-cron.yml
  platform_versioned_docs/version-24.2/enterprise/_templates/k8s/tower-svc.yml
  platform_versioned_docs/version-24.2/enterprise/data-studios.mdx
Labels: 1. Reviews complete

#425 Update Maintain role perms to include managing labels and resource labels
  platform_versioned_docs/version-24.1/orgs-and-teams/roles.mdx
  platform_versioned_docs/version-24.2/orgs-and-teams/roles.mdx
Labels: 1. Reviews complete

#421 [CLI] Remove erroneous "Data"
  platform_versioned_docs/version-24.2/cli/commands.mdx
Labels: 1. Dev/PM/SME

#405 EDU-8: Describe subdirectory data links
  platform_versioned_docs/version-24.2/data_studios/index.mdx
  platform_versioned_docs/version-24.2/data_studios/managing.mdx
Labels: 3. Reviews complete

#435 add fusion changelogs for v2.5.0 and v2.5.1
  changelog/fusion/v2.4.4.mdx
  changelog/fusion/v2.5.0.mdx
  changelog/fusion/v2.5.1.mdx
  changelog/seqera-cloud/v24.2.0_cycle28.mdx
Labels: 3. Reviews complete

#439 Improve CLI Commands page formatting, fix RHS ToC
  platform_versioned_docs/version-24.2/cli/commands.mdx
Labels: 1. Dev/PM/SME

#453 Add info about security scan false positives
  platform_versioned_docs/version-24.2/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
  platform_versioned_docs/version-24.3/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
Labels: 3. Reviews complete

#458 Update _redirects with new version
  static/_redirects
Labels: 3. Reviews complete

#454 Update with micromamba false error (due to verbose logging)
  platform_versioned_docs/version-24.2/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
  platform_versioned_docs/version-24.3/troubleshooting_and_faqs/data_studios_troubleshooting.mdx
Labels: 3. Reviews complete

#442 [PLAT-1205] Add pipeline image upload instructions
  platform_versioned_docs/version-24.2/getting-started/quickstart-demo/add-pipelines.mdx
  platform_versioned_docs/version-24.2/launch/launchpad.mdx
Labels: do not merge

#463 Release v24.3.0-cycle3_27f712a
  changelog/seqera-cloud/v24.3.0-cycle3_27f712a.mdx
Labels: 1. Editor review

#433 Studios sessions
  platform_versioned_docs/version-24.2/data_studios/index.mdx
  platform_versioned_docs/version-24.2/data_studios/managing.mdx
  platform_versioned_docs/version-24.2/orgs-and-teams/workspace-management.mdx
Labels: 3. Reviews complete

#477 [PLAT-628] Add academic and PoC usage limits admonition and CTA to contact sales
  platform_versioned_docs/version-24.2/limits/limits.mdx
  platform_versioned_docs/version-24.3/limits/limits.mdx
Labels: 1. Dev/PM/SME

#483 Add Fusion licensing content
  fusion_docs/guide.mdx
  fusion_docs/index.mdx
  fusion_docs/licensing.mdx
Labels: 1. Editor review, 1. Dev/PM/SME

#487 [Fusion licensing] Update sidebar.json
  fusion_docs/licensing.mdx
  fusion_docs/sidebar.json
Labels: 1. Editor review

#488 Update Fusion Snapshots docs with recommended EC2 instance types and sizing guidance
  fusion_docs/guide/snapshots.mdx
Labels: 1. Dev/PM/SME

#486 [Studios] Session duration
  platform_versioned_docs/version-24.3/data_studios/managing.mdx
Labels: 3. Reviews complete
