Repository seqeralabs/docs, pull requests merged in 2025-08, with the labels that each got.

#757 [fix] Removed 'data' reject - Vale
  .github/styles/config/vocabularies/Seqera/reject.txt
Labels: 1. Editor review

#747 data links to data-links
  platform-cloud/docs/data/data-explorer.md
  platform-enterprise_versioned_docs/version-23.4/data/data-explorer.md
  platform-enterprise_versioned_docs/version-24.1/data/data-explorer.md
  platform-enterprise_versioned_docs/version-24.2/data/data-explorer.md
  platform-enterprise_versioned_docs/version-25.1/data/data-explorer.md
Labels: 1. Editor review, 1. Dev/PM/SME

#752 [minor-fix] Incorrect spacing
  platform-cloud/docs/compute-envs/google-cloud.md
Labels: 1. Editor review

#755 [25.2] Changelog
  changelog/seqera-enterprise/v25.2.md
Labels: 1. Editor review, 1. Dev/PM/SME, enterprise-25.2

#771 Added Studios stuck in starting update
  platform-cloud/docs/troubleshooting_and_faqs/studios_troubleshooting.md
Labels: 1. Dev/PM/SME

#769 Change `TOWER_ENABLE_OPENAPI` default to `false`
  platform-enterprise_versioned_docs/version-23.1/enterprise/configuration/overview.md
  platform-enterprise_versioned_docs/version-23.3/enterprise/configuration/configtables/api.yml
  platform-enterprise_versioned_docs/version-23.3/enterprise/configuration/overview.mdx
  platform-enterprise_versioned_docs/version-23.4/enterprise/configuration/overview.mdx
  platform-enterprise_versioned_docs/version-24.1/enterprise/configuration/overview.mdx
  platform-enterprise_versioned_docs/version-24.2/enterprise/configuration/overview.mdx
  platform-enterprise_versioned_docs/version-25.1/enterprise/configuration/overview.mdx
  platform-enterprise_versioned_docs/version-25.2/enterprise/configuration/overview.mdx
Labels: 3. Reviews complete

#772 Internal link fixes
  platform-cloud/docs/credentials/agent_credentials.md
  platform-cloud/docs/getting-started/deployment-options.md
  platform-cloud/docs/supported_software/agent/overview.md
  platform-enterprise_versioned_docs/version-23.1/credentials/agent_credentials.md
  platform-enterprise_versioned_docs/version-23.1/getting-started/deployment-options.md
  platform-enterprise_versioned_docs/version-23.2/credentials/agent_credentials.md
  platform-enterprise_versioned_docs/version-23.2/getting-started/deployment-options.md
  platform-enterprise_versioned_docs/version-23.3/credentials/agent_credentials.md
  platform-enterprise_versioned_docs/version-23.3/getting-started/deployment-options.md
  platform-enterprise_versioned_docs/version-23.4/credentials/agent_credentials.md
  platform-enterprise_versioned_docs/version-23.4/getting-started/deployment-options.md
  platform-enterprise_versioned_docs/version-23.4/supported_software/agent/overview.md
  platform-enterprise_versioned_docs/version-24.1/credentials/agent_credentials.md
  platform-enterprise_versioned_docs/version-24.1/getting-started/deployment-options.md
  platform-enterprise_versioned_docs/version-24.1/supported_software/agent/overview.md
  platform-enterprise_versioned_docs/version-24.2/credentials/agent_credentials.md
  platform-enterprise_versioned_docs/version-24.2/getting-started/deployment-options.md
  platform-enterprise_versioned_docs/version-24.2/supported_software/agent/overview.md
  platform-enterprise_versioned_docs/version-25.1/credentials/agent_credentials.md
  platform-enterprise_versioned_docs/version-25.1/getting-started/deployment-options.md
  platform-enterprise_versioned_docs/version-25.1/supported_software/agent/overview.md
  platform-enterprise_versioned_docs/version-25.2/credentials/agent_credentials.md
  platform-enterprise_versioned_docs/version-25.2/getting-started/deployment-options.md
  platform-enterprise_versioned_docs/version-25.2/supported_software/agent/overview.md
Labels: 1. Editor review

#773 Fixed naming for Ent/Cloud
  platform-cloud/docs/studios/connect.md
  platform-enterprise_versioned_docs/version-25.2/studios/connect.md
Labels: 1. Dev/PM/SME

#734 Update Wave sidebar
  wave_docs/sidebar.json
Labels: 3. Reviews complete

#804 Update URL generation for platform paths
  scripts/indexDocs.js
Labels: 1. Editor review
